blueprint:
  name: Hilo AM Maintenance Heating
  description: Applies a maintenance temperature before AM Hilo pre-heating. Intended for non-Hilo thermostats (e.g. Sinopé).
  domain: automation
  input:
    enable_condition:
      name: Add Condition(s) if needed
      description: Add conditions if needed to run this automation. If ON or null the automation will run. 
      default: null
      selector:
        entity:
          domain: input_boolean
    thermostats:
      name: Thermostats
      description: The thermostats you want to configure with a maintenance period before the pre heating phase of a Hilo event.
      selector:
        target:
          entity:
            - domain: climate
    maintenance_temperature:
      name: Maintenance temperature
      default: 20
      selector:
        number:
          min: 15
          max: 25
          step: 0.5
          unit_of_measurement: °C
    maintenance_start:
      name: Maintenance start time
      default: "01:00:00"
      selector:
        time: {}
    maintenance_end:
      name: Maintenance end time
      default: "04:00:00"
      selector:
        time: {}
    # Enable temperature ramping    
    ramping_enabled:
      name: Enable gradual ramping
      default: true
      selector:
        boolean: {}
    ramp_step:
      name: Ramp step (°C)
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 1
          step: 0.1
          unit_of_measurement: °C
    ramp_delay:
      name: Ramp delay (minutes)
      default: 15
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: minutes

variables:
  enable_condition: !input enable_condition
  thermostats: !input thermostats
  maintenance_temperature: !input maintenance_temperature
  ramping_enabled: !input ramping_enabled
  ramp_step: !input ramp_step
  ramp_delay: !input ramp_delay

triggers:
  - trigger: time
    at: !input maintenance_start
    id: maintenance_start
  - trigger: state
    entity_id: sensor.defi_hilo
    to: pre_heat
    id: pre_heat

# Global condition for turning off automation (if applied).
condition:
  - condition: template
    value_template: >
      {{ enable_condition is none or is_state(enable_condition, 'on') }}
      
action:
  - choose:
      # Start maintenance ramp-up
      - conditions:
          - condition: trigger
            id: maintenance_start
          - condition: template
            value_template: >
              {{ state_attr('sensor.defi_hilo', 'next_events')[0].period == 'am' and states('sensor.defi_hilo') == 'scheduled' }}
        sequence:
          - choose:
              # If ramping is enabled
              - conditions:
                  - condition: template
                    value_template: "{{ ramping_enabled }}"
                sequence:
                  - variables:
                      target_temp: "{{ maintenance_temperature }}"
                      phase: "pre_heat"
                  - repeat:
                      while:
                        - condition: template
                          value_template: >
                            {{ state_attr(thermostats.entity_id | first, 'temperature') | float < target_temp
                               and states('sensor.defi_hilo') != phase }}
                      sequence:
                        - service: climate.set_temperature
                          target: !input thermostats
                          data:
                            temperature: >
                              {{ (state_attr(thermostats.entity_id | first, 'temperature') | float + ramp_step) | round(1) }}
                        - delay: 
                            minutes: "{{ ramp_delay }}"
              # Fallback: immediate set if ramping disabled
              - conditions: []
                sequence:
                  - service: climate.set_temperature
                    target: !input thermostats
                    data:
                      temperature: "{{ maintenance_temperature }}"

      # Stop maintenance when pre-heat starts
      - conditions:
          - condition: trigger
            id: pre_heat
        sequence:
          - service: climate.set_temperature
            target: !input thermostats
            data:
              temperature: >
                {{ state_attr('sensor.defi_hilo', 'next_events')[0].target_temperature }}
