blueprint:
  name: Hilo AM Maintenance Heating
  description: Applies a maintenance temperature before AM Hilo pre-heating. Intended for non-Hilo thermostats (e.g. Sinopé).
  domain: automation
  input:
    thermostats:
      name: Thermostats
      description: The thermostats you want to configure with a maintenance period before the pre heating phase of a Hilo event.
      selector:
        target:
          entity:
            - domain: climate
    enabled:
      name: Enable maintenance heating
      default: true
      selector:
        boolean: {}
    maintenance_temperature:
      name: Maintenance temperature
      selector:
        number:
          min: 15
          max: 25
          step: 0.5
          unit_of_measurement: °C
    maintenance_start:
      name: Maintenance start time
      default: "01:00:00"
      selector:
        time: {}
    maintenance_end:
      name: Maintenance end time
      default: "04:00:00"
      selector:
        time: {}

variables:
  enabled: !input enabled
  maintenance_temperature: !input maintenance_temperature
  thermostats: !input thermostats

triggers:
  - trigger: time
    at: !input maintenance_start
    id: maintenance_start
  - trigger: state
    entity_id: sensor.defi_hilo
    to: pre_heat
    id: pre_heat

actions:
  - choose:
    # Start maintenance heating
      - conditions:
          - condition: trigger
            id: maintenance_start
          - condition: template
            value_template: >
              {{ enabled and state_attr('sensor.defi_hilo', 'next_events')[0].period == 'am' and states('sensor.defi_hilo') == 'scheduled' }}
        sequence:
          - service: climate.set_temperature
            target: !input thermostats
            data:
              temperature: "{{ maintenance_temperature }}"

      # Stop maintenance when pre-heat starts
      - conditions:
          - condition: trigger
            id: pre_heat
        sequence:
          - service: climate.set_temperature
            target: !input thermostats
            data:
              temperature: >
                {{ state_attr('sensor.defi_hilo', 'next_events')[0].target_temperature }}
